### ISSUE TITLE
Errror in index.scss laoder 

### ISSUE THREAD

**Issue by alghouliammar1** [hidglobal/digitalpersona-sample-angularjs#11]
**After all the installation steps when I run code this error faces me**   **Can any one help me out get over this problem please** 
`ERROR in ./src/index.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./src/index.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

$navbar-padding-horizontal:        floor(math.div($grid-gutter-width, 2)) !default;
                                            ^
      Invalid CSS after "...     floor(math": expected expression (e.g. 1px, bold), was ".div($grid-gutter-w"
      in C:\Users\amar\Desktop\digitalpersonaAngular\digitalpersona-sample-angularjs\node_modules\bootstrap-sass\assets\stylesheets\bootstrap\_variables.scss (line 369, column 46)
 @ ./src/index.scss 2:14-118
 @ ./src/index.ts
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [0] ./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html 2.41 KiB {0} [built]
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! example-angularjs@1.0.6 build-dev: `webpack --config build/webpack/dev.js --NODE_ENV=dev`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the example-angularjs@1.0.6 build-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

**Comment by a-bronx** [comment]
26c7e5e2ff1ae5920c60a4be021c5958f5cecb75 should fix this, after webpack upgrade.
