### ISSUE TITLE
This Sample not Run

### ISSUE THREAD

**Issue by radhe65gupta** [hidglobal/digitalpersona-sample-angularjs#14]
This Sample Not Work,So I can"t See this Sample OutPut. 
And aslo
I have digital persona 4500 Fingerprint reader and i want to integration on asp.net core web app.How can i do it?

**Comment by a-bronx** [comment]
Not enough information to reproduce the problem.

For integration with AspNet Core Web App, you can use the same client, but you'll need to write your own server. The server should use [Digitalpersona Access Management Web Services](https://hidglobal.github.io/digitalpersona-access-management-services/index.html) in a similar way as it does the NodeJS server in this sample. Unfortunately, there are no .NET wrappers for DPAM Web Services, but they should be pretty straightforward to write, using @digitalpersona/*  JS/TS libraries as a reference (it is mostly data conversion and error propagation code).
