### ISSUE TITLE
Prerequisites

### ISSUE THREAD

**Issue by Aragon-Diego** [hidglobal/digitalpersona-sample-angularjs#6]
Do you have the links for the prerequisites?

- Windows ADAM Service (LDS)
- DigitalPersona LDS Server (DP LDS Server)
- DigitalPersona LDS Administration Tools (DP LDS AT)
- DigitalPersona LDS Web Management Components (DP LDS WMC)

I wasn't able to find them by my own

**Comment by Aragon-Diego** [comment]
I'm using a HID Lumidigm M321-00

Model: M321-00
Serial #: 172246
Part #: 001053G

**Comment by a-bronx** [comment]
Hello,

You can find datasheets and guides on the HID Global site, in the [HID DigitalPersona Software](https://www.hidglobal.com/products/software/digitalpersona/digitalpersona) section.

In particular, you can look into the [datasheet](https://www.hidglobal.com/sites/default/files/resource_files/iams-hid-digitalpersona-ds-en.pdf) for a high-level prerequisites, or into the [HID DigitalPersona LDS Administration Guide](https://www.hidglobal.com/sites/default/files/resource_files/hid-digitalpersona-lds-administrator-guide_0.pdf?utm_source=crossmatch.com&utm_campaign=crossmatch.com&utm_medium=301) for more detailed outline.

Also feel free inquire our [Customer Support team](https://iamsportal.hidglobal.com/)

**Comment by Aragon-Diego** [comment]
Tnks:)
